apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-mysql
  labels:
    app.kubernetes.io/managed-by: Moonscale
automountServiceAccountToken: false
secrets:
  - name: my-mysql
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    janitor/ttl: {{ resource_ttl }}m
  name: moonscale-instance-{{ name }}
  labels:
    app.kubernetes.io/instance: {{ name }}
    app.kubernetes.io/managed-by: Moonscale
    app.kubernetes.io/name: moonscale-instance-{{ name }}
type: Opaque
data:
  mysql-root-password: "{{ root_password }}"
  mysql-password: "{{ root_password }}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: moonscale-instance-{{ name }}
  annotations:
    janitor/ttl: {{ resource_ttl }}m
  labels:
    app.kubernetes.io/managed-by: Moonscale
    app.kubernetes.io/instance: {{ name }}
data:
  my.cnf: |-
    [mysqld]
    default_authentication_plugin=mysql_native_password
    skip-name-resolve
    explicit_defaults_for_timestamp
    basedir=/opt/bitnami/mysql
    plugin_dir=/opt/bitnami/mysql/lib/plugin
    port= 3306
    socket=/opt/bitnami/mysql/tmp/mysql.sock
    datadir=/bitnami/mysql/data
    tmpdir=/opt/bitnami/mysql/tmp
    max_allowed_packet=16M
    bind-address=*
    pid-file=/opt/bitnami/mysql/tmp/mysqld.pid
    log-error=/opt/bitnami/mysql/logs/mysqld.log
    character-set-server=UTF8
    slow_query_log=0
    long_query_time=10.0
    auto_generate_certs=ON
    max_connections=10000


    [client]
    port=3306
    socket=/opt/bitnami/mysql/tmp/mysql.sock
    default-character-set=UTF8
    plugin_dir=/opt/bitnami/mysql/lib/plugin

    [manager]
    port=3306
    socket=/opt/bitnami/mysql/tmp/mysql.sock
    pid-file=/opt/bitnami/mysql/tmp/mysqld.pid
---
apiVersion: v1
kind: Service
metadata:
  name: moonscale-instance-{{ name }}-headless
  labels:
    app.kubernetes.io/managed-by: Moonscale
    app.kubernetes.io/instance: {{ name }}
  annotations:
    janitor/ttl: {{ resource_ttl }}m
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql
  selector:
    app.kubernetes.io/instance: {{ name }}
    app.kubernetes.io/name: moonscale-instance-{{ name }}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    janitor/ttl: {{ resource_ttl }}m
  name: moonscale-instance-{{ name }}
  labels:
    app.kubernetes.io/managed-by: Moonscale
    app.kubernetes.io/instance: {{ name }}
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: mysql
      port: 3306
      protocol: TCP
      targetPort: mysql
      nodePort: null
  selector:
    app.kubernetes.io/instance: {{ name }}
    app.kubernetes.io/name: moonscale-instance-{{ name }}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    janitor/ttl: {{ resource_ttl }}m
  name: moonscale-instance-{{ name }}-ps
  labels:
    app.kubernetes.io/managed-by: Moonscale
    app.kubernetes.io/instance: {{ name }}
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: planetscale-api
      port: 3900
      protocol: TCP
      targetPort: planetscale-api
      nodePort: null
  selector:
    app.kubernetes.io/instance: {{ name }}
    app.kubernetes.io/name: moonscale-instance-{{ name }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    janitor/ttl: {{ resource_ttl }}m
  labels:
    app.kubernetes.io/managed-by: Moonscale
    app.kubernetes.io/instance: {{ name }}
  name: moonscale-instance-{{ name }}
spec:
  rules:
    - host: moonscale-instance-{{ name }}.{{ domain }}
      http:
        paths:
          - backend:
              service:
                name: moonscale-instance-{{ name }}-ps
                port:
                  name: planetscale-api
            path: /
            pathType: Prefix
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    janitor/ttl: {{ resource_ttl }}m
  name: moonscale-instance-{{ name }}
  labels:
    app.kubernetes.io/managed-by: Moonscale
    app.kubernetes.io/instance: {{ name }}
spec:
  replicas: 1
  podManagementPolicy: ""
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ name }}
      app.kubernetes.io/name: moonscale-instance-{{ name }}
  serviceName: my-mysql
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ name }}
        app.kubernetes.io/managed-by: Moonscale
        app.kubernetes.io/name: moonscale-instance-{{ name }}
    spec:
      serviceAccountName: my-mysql

      automountServiceAccountToken: false
      affinity:
        podAffinity:

        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/instance: {{ name }}
                    app.kubernetes.io/name: moonscale-instance-{{ name }}
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:

      securityContext:
        fsGroup: 1001
        fsGroupChangePolicy: Always
        supplementalGroups: []
        sysctls: []
      initContainers:
      containers:
        - image: ghcr.io/mattrobenolt/ps-http-sim:latest
          imagePullPolicy: IfNotPresent
          name: planetscale-proxy
          args:
            [
              "-listen-port=3900",
              "-mysql-dbname=planetscale",
              "-mysql-addr=localhost",
            ]
          ports:
            - containerPort: 3900
              name: planetscale-api
              protocol: TCP
          resources:
            requests:
              cpu: 250m
              memory: 256Mi

        - name: mysql
          image: docker.io/bitnami/mysql:8.0.36-debian-12-r8
          imagePullPolicy: "IfNotPresent"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: false
            runAsGroup: 0
            runAsNonRoot: true
            runAsUser: 1001
            seLinuxOptions: null
            seccompProfile:
              type: RuntimeDefault
          env:
            - name: BITNAMI_DEBUG
              value: "false"
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: moonscale-instance-{{ name }}
                  key: mysql-root-password
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_DATABASE
              value: "planetscale"
          envFrom:
          ports:
            - name: mysql
              containerPort: 3306
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
            exec:
              command:
                - /bin/bash
                - -ec
                - |
                  password_aux="${MYSQL_ROOT_PASSWORD:-}"
                  if [[ -f "${MYSQL_ROOT_PASSWORD_FILE:-}" ]]; then
                      password_aux=$(cat "$MYSQL_ROOT_PASSWORD_FILE")
                  fi
                  mysqladmin status -uroot -p"${password_aux}"
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
            exec:
              command:
                - /bin/bash
                - -ec
                - |
                  password_aux="${MYSQL_ROOT_PASSWORD:-}"
                  if [[ -f "${MYSQL_ROOT_PASSWORD_FILE:-}" ]]; then
                      password_aux=$(cat "$MYSQL_ROOT_PASSWORD_FILE")
                  fi
                  mysqladmin status -uroot -p"${password_aux}"
          startupProbe:
            failureThreshold: 10
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
            exec:
              command:
                - /bin/bash
                - -ec
                - |
                  password_aux="${MYSQL_ROOT_PASSWORD:-}"
                  if [[ -f "${MYSQL_ROOT_PASSWORD_FILE:-}" ]]; then
                      password_aux=$(cat "$MYSQL_ROOT_PASSWORD_FILE")
                  fi
                  mysqladmin status -uroot -p"${password_aux}"
          volumeMounts:
            - name: data
              mountPath: /bitnami/mysql
            - name: empty-dir
              mountPath: /tmp
              subPath: tmp-dir
            - name: empty-dir
              mountPath: /opt/bitnami/mysql/conf
              subPath: app-conf-dir
            - name: empty-dir
              mountPath: /opt/bitnami/mysql/tmp
              subPath: app-tmp-dir
            - name: empty-dir
              mountPath: /opt/bitnami/mysql/logs
              subPath: app-logs-dir
            - name: config
              mountPath: /opt/bitnami/mysql/conf/my.cnf
              subPath: my.cnf
      volumes:
        - name: config
          configMap:
            name: moonscale-instance-{{ name }}
        - name: empty-dir
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        annotations:
          janitor/ttl: {{ resource_ttl }}m
        name: data
        labels:
          app.kubernetes.io/instance: {{ name }}
          app.kubernetes.io/name: moonscale-instance-{{ name }}
          app.kubernetes.io/managed-by: Moonscale
      spec:
        accessModes:
          - "ReadWriteOnce"
        storageClassName: "cinder-generic-nvme"
        resources:
          requests:
            storage: "{{ pvc_size }}"
